// .claude/skills/talos-design/components/data-display/MetricCard.jsx
import React from "react";

export function MetricCard({ label, value, color = "var(--text-primary)", onClick }) {
  const Tag = onClick ? "button" : "div";
  return (
    <Tag
      onClick={onClick}
      style={{
        textAlign: "left",
        background: "var(--surface-card)",
        border: "1px solid var(--border-default)",
        borderRadius: "var(--r-lg)",
        padding: 14,
        cursor: onClick ? "pointer" : "default",
        width: "100%",
        boxSizing: "border-box",
      }}
    >
      <div
        style={{
          font: "600 11px var(--font-ui)",
          color: "var(--text-muted)",
          marginBottom: 8,
          whiteSpace: "nowrap",
          overflow: "hidden",
          textOverflow: "ellipsis",
        }}
      >
        {label}
      </div>
      <div style={{ font: "700 24px var(--font-mono)", color }}>{value}</div>
    </Tag>
  );
}

// apps/web/src/app/shared/metric-card/metric-card.component.ts
// SPDX-FileCopyrightText: 2026 Vulkan Technologies
// SPDX-License-Identifier: AGPL-3.0-or-later

import { Component, input } from '@angular/core';

/** Talos design system MetricCard (components/data-display/MetricCard.jsx). `value` is always a
 * real computed figure -- never an estimate (CLAUDE.md "Numbers are real"). */
@Component({
  selector: 'app-metric-card',
  template: `
    <div class="metric-card">
      <div class="label">{{ label() }}</div>
      <div class="value" [style.color]="color()">{{ value() }}</div>
    </div>
  `,
  styles: `
    .metric-card {
      text-align: left;
      background: var(--surface-card);
      border: 1px solid var(--border-default);
      border-radius: var(--r-lg);
      padding: 14px;
      width: 100%;
      box-sizing: border-box;
    }

    .label {
      font: var(--weight-semibold) var(--text-xs) var(--font-ui);
      color: var(--text-muted);
      margin-bottom: 8px;
      white-space: nowrap;
      overflow: hidden;
      text-overflow: ellipsis;
    }

    .value {
      font: var(--weight-bold) var(--text-2xl) var(--font-mono);
      color: var(--text-primary);
    }
  `,
})
export class MetricCardComponent {
  readonly label = input.required<string>();
  readonly value = input.required<string | number>();
  readonly color = input<string>('var(--text-primary)');
}
