// .claude/skills/talos-design/components/badges/AgentBadge.jsx
import React from "react";

const AGENTS = {
  "claude-code": { label: "Claude Code", initial: "C", fg: "#A78BFA", border: "rgba(139,92,246,0.3)" },
  "codex-cli": { label: "Codex CLI", initial: "X", fg: "#38BDF8", border: "rgba(56,189,248,0.3)" },
  "opencode": { label: "OpenCode", initial: "O", fg: "#22C55E", border: "rgba(34,197,94,0.3)" },
  "openhands": { label: "OpenHands", initial: "H", fg: "#F59E0B", border: "rgba(245,158,11,0.3)" },
  "custom-shell": { label: "Custom Shell", initial: "S", fg: "var(--text-secondary)", border: "rgba(160,167,181,0.3)" },
};

export function AgentBadge({ agentKey = "custom-shell" }) {
  const a = AGENTS[agentKey] || AGENTS["custom-shell"];
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        padding: "3px 9px 3px 7px",
        borderRadius: "var(--r-xs)",
        font: "600 11px/1.5 var(--font-ui)",
        whiteSpace: "nowrap",
        background: "var(--surface-elevated)",
        color: a.fg,
        border: `1px solid ${a.border}`,
      }}
    >
      <span
        style={{
          width: 14,
          height: 14,
          borderRadius: 4,
          background: a.fg,
          flex: "none",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          font: "700 8px var(--font-mono)",
          color: "var(--surface-elevated)",
        }}
      >
        {a.initial}
      </span>
      {a.label}
    </span>
  );
}

// apps/web/src/app/shared/badges/agent-badge.component.ts
// SPDX-FileCopyrightText: 2026 Vulkan Technologies
// SPDX-License-Identifier: AGPL-3.0-or-later

import { Component, computed, input } from '@angular/core';

/** Talos design system AgentBadge (components/badges/AgentBadge.jsx), keyed by the registered
 * adapter keys from talos.schema.json's agentKey enum (CLAUDE.md's adapter order). */
interface AgentVisual {
  label: string;
  initial: string;
  color: string;
  border: string;
}

const AGENTS: Record<string, AgentVisual> = {
  'claude-code': { label: 'Claude Code', initial: 'C', color: '#A78BFA', border: 'rgba(139,92,246,0.3)' },
  'codex-cli': { label: 'Codex CLI', initial: 'X', color: '#38BDF8', border: 'rgba(56,189,248,0.3)' },
  opencode: { label: 'OpenCode', initial: 'O', color: '#22C55E', border: 'rgba(34,197,94,0.3)' },
  openhands: { label: 'OpenHands', initial: 'H', color: '#F59E0B', border: 'rgba(245,158,11,0.3)' },
  'custom-shell': { label: 'Custom Shell', initial: 'S', color: 'var(--text-secondary)', border: 'rgba(160,167,181,0.3)' },
};

const FALLBACK: AgentVisual = AGENTS['custom-shell'];

@Component({
  selector: 'app-agent-badge',
  template: `
    <span class="agent-badge" [style.color]="agent().color" [style.border-color]="agent().border">
      <span class="mark" [style.background]="agent().color">{{ agent().initial }}</span>
      {{ agent().label }}
    </span>
  `,
  styles: `
    .agent-badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 3px 9px 3px 7px;
      border-radius: var(--r-xs);
      font: var(--weight-semibold) var(--text-xs) var(--font-ui);
      white-space: nowrap;
      background: var(--surface-elevated);
      border: 1px solid transparent;
    }

    .mark {
      width: 14px;
      height: 14px;
      border-radius: 4px;
      flex: none;
      display: flex;
      align-items: center;
      justify-content: center;
      font: var(--weight-bold) 8px var(--font-mono);
      color: var(--surface-elevated);
    }
  `,
})
export class AgentBadgeComponent {
  readonly agentKey = input.required<string>();
  protected readonly agent = computed(() => AGENTS[this.agentKey()] ?? FALLBACK);
}
